### ISSUE TITLE
TypeError: 'PaddedBatchDataset' object is not subscriptable

### ISSUE THREAD

**Issue by mjhanphd** [WindQAQ/listen-attend-and-spell#3]
Hey
I tried to run LAS with Librispeech dataset but I've run into an error.
Please look at below.

(tensorflow3.5) [myoungji.han@login03 las]$ python train.py --train ../deepSpeech/data/librispeech/processed/test-clean/test-clean.tfrecords --vocab ./misc/eng-char.table --model_dir ./model_libri
INFO:tensorflow:Using config: {'_tf_random_seed': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x2aefb5a72d30>, '_is_chief': True, '_num_worker_replicas': 1, '_model_dir': './model_libri', '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_task_id': 0, '_save_checkpoints_steps': None, '_log_step_count_steps': 100, '_service': None, '_num_ps_replicas': 0, '_master': '', '_session_config': None, '_task_type': 'worker', '_save_checkpoints_secs': 600, '_save_summary_steps': 100}
Traceback (most recent call last):
  File "train.py", line 116, in <module>
    main(args)
  File "train.py", line 107, in main
    input_fn=lambda: input_fn(
  File "/home/sr5/myoungji.han/tensorflow3.5/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/sr5/myoungji.han/tensorflow3.5/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 711, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/sr5/myoungji.han/tensorflow3.5/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/sr5/myoungji.han/las/model_helper.py", line 77, in las_model_fn
    encoder_inputs = features['encoder_inputs']
TypeError: 'PaddedBatchDataset' object is not subscriptable

I cannot figure out what's the problem.
Could you give me a help?

**Comment by WindQAQ** [comment]
Hello, I re-check the type of `features`, and it is a dict. Moreover, I print `features` in `las_model_fn`, and get 
```
{'encoder_inputs': <tf.Tensor 'IteratorGetNext:0' shape=(?, ?, 39) dtype=float32>, 'source_sequence_length': <tf.Tensor 'IteratorGetNext:1' shape=(?,) dtype=int32>}
```
which is exactly subscriptable. Could you print out `features` to get more information? Or do you modify `utils/dataset_utils.py`?

Also, it seems that you use this [deepSpeech](https://github.com/fordDeepDSP/deepSpeech/blob/master/code/preprocess_LibriSpeech.py) to process data. I will give it a try when I am available. It's sorry that I have some works to do recently...

**Comment by mjhanphd** [comment]
I modified the source code of deepSpeech a little bit to fit the requirements of your model.
I actually have succeeded to test with the same configuration in one machine, but this issue occurred when I tried it on another machine.
I think I need to check carefully again.

**Comment by WindQAQ** [comment]
Maybe it is the problem of tensorflow's version? Dataset and Estimator API varies version by version, which is quite annoying. Anyway, as specified in `requirements.txt`, I use tensorflow==1.8.0, and it works well on my machine.

**Comment by mjhanphd** [comment]
Now I have checked tensorflow versions of my two different machines, one that worked out well have
tensorflow 1.8.0 and one with a problem have tensorflow 1.4.1.
I believe this is the problem spot.
I'll re-install tensorflow and try again. Thanks:)

**Comment by WindQAQ** [comment]
Okay, thank for testing other versions of tensorflow by the way :)
