### ISSUE TITLE
Difference between, decoder_inputs and targets

### ISSUE THREAD

**Issue by ajinkyaT** [WindQAQ/listen-attend-and-spell#4]
Hi!,

Thanks for open sourcing your project. I have a doubt, in "model_helper.py",  you defined decoder_inputs = labels['targets_inputs'] and targets = labels['targets_outputs'] can I know what the difference between two and what do they mean? Or are they same thing, ids of words or characters?

**Comment by WindQAQ** [comment]
Hello,

They are quite similar, but the only difference is that `targets_inputs` field starts with `SOS_ID`, and `targets_outputs` ends with `EOS_ID`.

Consider ground truth `[4, 5, 6, 7, 8]`, and then `targets_inputs` is `[SOS_ID, 4, 5, 6, 7, 8]`; `targets_outputs` is `[4, 5, 6, 7, 8, EOS_ID]`, where I omit padding for clarity.

This processing is the same with [tensorflow nmt](https://github.com/tensorflow/nmt), and you can see [this line](https://github.com/WindQAQ/listen-attend-and-spell/blob/master/utils/dataset_utils.py#L54) in my repo for more details.

**Comment by ajinkyaT** [comment]
Thanks for your prompt reply!

**Comment by WindQAQ** [comment]
Feel free to contact me if you have other questions :)
And I'm gonna close this issue BTW.
