### ISSUE TITLE
Treating space as vocabulary

### ISSUE THREAD

**Issue by mjhanphd** [WindQAQ/listen-attend-and-spell#5]
I want to build a grapheme-based las model where each English characters are treated as output symbols.
This model has to treat the space as a separate output symbol.
How could I achieve this?
A naïve way would be preprocessing the transcriptions so that all spaces are replaced with a special symbol, say '*', and including * in the vocab list.
Is there any smarter way to do this?

**Comment by WindQAQ** [comment]
If you really do not want to replace spaces with other symbols, you can try to modify the code [this line](https://github.com/WindQAQ/listen-attend-and-spell/blob/master/utils/vocab_utils.py#L25).

Simply modify
```python
vocab_list = [vocab.strip('\r\n ') for vocab in f]
``` 
to 
```python
vocab_list = [vocab.strip('\r\n') for vocab in f]
```

That is, do not strip out ' ' for each vocab in vocabulary table because you want to keep a space in the vocabulary table. Note that if you do it, remember to check that the vocabulary file you created **does not have any leading and trailing space** excepting ' ' token itself!

Thank you :)

**Comment by mjhanphd** [comment]
Actually, I've already done exactly the way you mentioned.
But after that, when I print the vocab_list, it printed out [..., 'Z', ''] where the last '' was supposed to be the space.

**Comment by WindQAQ** [comment]
Do you actually modify the code I mentioned above?

Here is my testing result on my computer, and it works well for me.

![image](https://user-images.githubusercontent.com/11615393/42677588-c5ba0984-86ae-11e8-84fa-5d0b064489bd.png)

**Comment by mjhanphd** [comment]
Right after I posted the last comment I realized that I made a mistake and confirmed that it works well.
Thanks :)

**Comment by WindQAQ** [comment]
It's OK :)
Free free to ask me if there is any problem.

**Comment by mjhanphd** [comment]
By the way, your timit recipe seems to not deal with the space.
Considering that spaces occur very often and also they serve an important role in sentence, like separating different words, so isn't it more intuitive to include the space as one of the vocabularies?
If not, "banana is yellow" for example will be treated as just "bananaisyellow", which is expected to cause some trouble.
And this is the same with the phoneme case like TIMIT!

**Comment by WindQAQ** [comment]
In TIMIT case, it exactly do no consider the space. But some of phonemes are served as *silence* while  mapping to 39 phone classes. Hence, I do think that these phones may represent space to some extent when predicting them (though I am not a linguist LOL).

See [this paper](http://cdn.intechopen.com/pdfs/15948/InTech-Phoneme_recognition_on_the_timit_database.pdf) for more details.
